### ISSUE TITLE
GCC compilation

### ISSUE THREAD

**Issue by NLCharles** [sshaoshuai/Pointnet2.PyTorch#1]
May I post a question?
I noticed when using CUDA 8.0, which requires gcc 4.8, compilation warnings emerge. _I wonder what your gcc version is._ If using default gcc on Ubuntu 16.04 it should be gcc 6.

**Comment by sshaoshuai** [comment]
I have tested it with GCC 5.4.0 and GCC 4.9.4, both of them are ok.

**Comment by NLCharles** [comment]
Dear Shaoshuai,
I am Wentao Qian in IOFC. I am glad to see you released the model yesterday.
Did you give out the complete version of source code? It seems most of the
parts are in their place. I have run the three 'setup.py' files and are
ready to test your model once the training for another model is over.
Thank you very much for your instant reply!
Yours sincerely,
Wentao Qian

**Comment by NLCharles** [comment]
Dear Shaoshuai,
I will go for gcc 5 if gcc 4.8 is unable to work. Thank you!
Yours,
Charles(Qian Wentao)

**Comment by sshaoshuai** [comment]
Dear Wentao, 
The released codes are complete for all the steps mentioned in the paper. 

Thanks, 
Shaoshuai
