### ISSUE TITLE
ModuleNotFoundError: No module named 'pointnet2_cuda'

### ISSUE THREAD

**Issue by BasserJason** [sshaoshuai/Pointnet2.PyTorch#12]
Why does it happen? I can't find pointnet2_cuda

**Comment by BasserJason** [comment]
i got it. My setup.py didn't install correctly.

**Comment by JianrongYan** [comment]
> i got it. My setup.py didn't install correctly.
so how to solve it.

**Comment by fzhiheng** [comment]
> > so how to solve it.
I met the same problem, have you solved it?

**Comment by JianrongYan** [comment]
> 
> > > so how to solve it.
> > > I met the same problem, have you solved it?
you can try using pip install setuptools==58.2.0 to lower your setuptool version. Besides, ninja lib is necessary.

**Comment by fzhiheng** [comment]
> > > > you can try using pip install setuptools==58.2.0 to lower your setuptool version. Besides, ninja lib is necessary.
It works! Thanks a lot!
