### ISSUE TITLE
what does radius represent?

### ISSUE THREAD

**Issue by LiuFG** [sshaoshuai/Pointnet2.PyTorch#14]
In set abstraction layer, there is a config named RADIUS
` RADIUS: [[0.1, 0.5], [0.5, 1.0], [1.0, 2.0], [2.0, 4.0]]`
It means Euclidean distance? or a ratio of the number of point(e.g. 0.1\*4096)？

**Comment by andraspalffy** [comment]
This is used in 
`pointnet2/pointnet2_utils.py`, in the init function of `class QueryAndGroup(nn.Module):`

`param radius: float, radius of ball`

So it is indeed Euclidean radius. 

(Sorry I know t is an old question, but may be useful for others)
