### ISSUE TITLE
Error while installing pointnet2

### ISSUE THREAD

**Issue by pvnieo** [sshaoshuai/Pointnet2.PyTorch#17]
Hi,
I'm using pytorch 1.5. I was installing pointnet2 in a virtualenv, using `python3 setup.py install`, and I got the following error:
```
src/ball_query.cpp:22:27: error: ‘THCState_getCurrentStream’ was not declared in this scope
   22 |     cudaStream_t stream = THCState_getCurrentStream(state);
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Can you give me hints on how to solve this?
Thank you in advance!

**Comment by parkchaesong** [comment]
Hi! I'm in same problem now.
If you solved it, could you share the solution?
